# Generated by Django 4.2.7 on 2023-12-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, default='default/default_item.png', null=True, upload_to='items/'),
        ),
    ]
