# Generated by Django 4.2.7 on 2023-12-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_slug_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, default='default/default-item.jpg', null=True, upload_to='items/'),
        ),
    ]
