# Generated by Django 4.2.7 on 2023-12-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uuid',
            new_name='id',
        ),
    ]
