# Generated by Django 4.2.7 on 2023-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/', verbose_name='画像'),
        ),
    ]
