# Generated by Django 4.2.7 on 2023-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='default/default-item.jpg', null=True, upload_to='reviews/', verbose_name='画像'),
        ),
    ]
